name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: lint-node-modules-cache-${{ github.sha }}
          restore-keys: lint-node-modules-cache-
      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: actions/cache@v3
        with:
          path: node_modules/.cache
          key: test-node-modules-cache-${{ github.sha }}
          restore-keys: test-node-modules-cache-
      - run: npm install
      - run: npm run test
